
name = "tcgtoolws-worker"
compatibility_date = "2025-09-24"
pages_build_output_dir = "dist"

[dev]
port = 8788

[[d1_databases]]
binding = "DB"
database_name = "ws-account-db"
database_id = "8368900c-fb02-483c-8f71-43882ec6ab6b"