export const seriesMap = {
  'Re：从零开始的异世界生活': {
    id: 're0',
    prefixes: ['RZ'],
    icon: 're0.webp',
  },
  '富士见Fantasia文库': {
    id: 'fantasia',
    prefixes: [
      'F35',
      'Fab',
      'Fcr',
      'Fdd',
      'Fdl',
      'Fdy',
      'Ffp',
      'Fgc',
      'Fgi',
      'Fgm',
      'Fhc',
      'Fii',
      'Fil',
      'Fjk',
      'Fkd',
      'Fkk',
      'Fkm',
      'Fkn',
      'Fks',
      'Fkz',
      'Fma',
      'Fmr',
      'Foo',
      'Fos',
      'Foy',
      'Fra',
      'Fsa',
      'Fsh',
      'Fsi',
      'Fsl',
      'Fsp',
      'Fsr',
      'Ftr',
      'Ftt',
      'Fvd',
    ],
    icon: 'fantasia.webp',
  },
  '女神异闻录': {
    id: 'persona',
    prefixes: ['P3', 'P4', 'PQ', 'P5'],
    icon: 'persona.webp',
  },
}
