export const seriesMap = {
  'Re：从零开始的异世界生活': {
    id: 're0',
    prefixes: ['RZ'],
    icon: 're0.webp',
  },
  '富士见Fantasia文库': {
    id: 'fantasia',
    prefixes: [
      'F35',
      'Fab',
      'Fcr',
      'Fdd',
      'Fdl',
      'Fdy',
      'Ffp',
      'Fgc',
      'Fgi',
      'Fgm',
      'Fhc',
      'Fii',
      'Fil',
      'Fjk',
      'Fkd',
      'Fkk',
      'Fkm',
      'Fkn',
      'Fks',
      'Fkz',
      'Fma',
      'Fmr',
      'Foo',
      'Fos',
      'Foy',
      'Fra',
      'Fsa',
      'Fsh',
      'Fsi',
      'Fsl',
      'Fsp',
      'Fsr',
      'Ftr',
      'Ftt',
      'Fvd',
    ],
    icon: 'fantasia.webp',
  },
  '女神异闻录': {
    id: 'persona',
    prefixes: ['P3', 'P4', 'PQ', 'P5'],
    icon: 'persona.webp',
  },
  '莉可丽丝': {
    id: 'lrc',
    prefixes: ['LRC'],
    icon: 'lrc.webp',
  },
  '少女乐队的呐喊': {
    id: 'gbc',
    prefixes: ['GCR'],
    icon: 'gbc.webp',
  },
  '足球小将': {
    id: 'ctb',
    prefixes: ['CTB'],
    icon: 'ctb.webp',
  },
  '蜡笔小新': {
    id: 'cs',
    prefixes: ['CS'],
    icon: 'cs.webp',
  },
  '摇曳露营': {
    id: 'yrc',
    prefixes: ['YRC'],
    icon: 'yrc.webp',
  },
  '里世界郊游': {
    id: 'rsk',
    prefixes: ['RSK'],
    icon: 'rsk.webp',
  },
  'BanG Dream!': {
    id: 'bd',
    prefixes: ['BD'],
    icon: 'bd.webp',
  },
  '缘结甘神家': {
    id: 'amg',
    prefixes: ['AMG'],
    icon: 'amg.webp',
  },
  '世界计划 彩色舞台 feat.初音未来': {
    id: 'pjs',
    prefixes: ['PJS'],
    icon: 'pjs.webp',
  },
  '青桐高校': {
    id: 'aoh',
    prefixes: ['AOH'],
    icon: 'aoh.webp',
  },
  'Love Live! 莲之空女学院学园偶像俱乐部': {
    id: 'lhs',
    prefixes: ['LHS'],
    icon: 'lhs.webp',
  },
}
